# Generated by Django 4.1.3 on 2023-12-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busBookingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bususer',
            name='userType',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
